FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN mkdir -p prisma/data

EXPOSE 5000

CMD sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"